apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd                    # Les Applications ArgoCD vivent dans ce namespace
spec:
  project: default
  source:
    chart: vault                       # Nom du chart Helm (pas un path Git !)
    repoURL: https://helm.releases.hashicorp.com  # Registre Helm HashiCorp
    targetRevision: 0.28.1             # Version du chart (pas de Vault)
    helm:
      releaseName: vault               # Nom de la release Helm
      values: |                        # Values Helm inline (equivalent de values.yaml)
        server:
          affinity: ""                 # Desactive l'anti-affinity (obligatoire sur minikube, 1 seul noeud)
          ha:
            enabled: true              # Mode High Availability
            replicas: 3                # 3 replicas pour le quorum Raft
            raft:
              enabled: true            # Stockage Raft integre (pas besoin de Consul)
              ...
          dataStorage:
            storageClass: standard     # StorageClass minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true