apiVersion: v1
kind: ConfigMap
metadata:
  # On utilise le helper pour le nom, comme dans ton Deployment
  name: {{ include "miage-bank.fullname" . }}-config
  labels:
    {{- include "miage-bank.labels" . | nindent 4 }}
data:
  # Données non-sensibles uniquement
  DB_URL: {{ .Values.env.DB_URL | quote }}
  APP_PROFILE: {{ .Values.env.APP_PROFILE | default "prod" | quote }}
  LOG_LEVEL: "INFO"