apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "miage-bank.fullname" . }}-config
  labels:
    {{- include "miage-bank.labels" . | nindent 4 }}
data:
  # On met des valeurs par défaut pour éviter les erreurs "nil pointer"
  DB_URL: "jdbc:mysql://miage-bank-db:3306/miage_db"
  APP_PROFILE: "dev"
  LOG_LEVEL: "INFO"
  CONFIG_SERVER_URL: "http://miage-bank-configserver:10003"