{{- range $key, $service := .Values.microservices }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $service.name }}
spec:
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
    spec:
      containers:
        - name: {{ $service.name }}
          image: "{{ $service.repository }}:{{ $service.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ $service.port }}
          env:
            # Toutes les applis Java cherchent ces deux-là
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://{{ $.Release.Name }}-configserver:10003"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://{{ $.Release.Name }}-annuaire:10001/eureka/"
            
            # Condition pour MySQL (Service Clients)
            {{- if eq $service.dbType "mysql" }}
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://miage-bank-db:3306/miage_db?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: miage-bank-db-secret
                  key: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: miage-bank-db-secret
                  key: DB_PASSWORD
            {{- end }}

            # Condition pour MongoDB (Service Comptes)
            {{- if eq $service.dbType "mongodb" }}
            - name: SPRING_DATA_MONGODB_HOST
              value: "miage-bank-mongodb"
            {{- end }}

          # On garde les sondes de santé car c'est obligatoire en MIAGE
          startupProbe:
            httpGet:
              path: /actuator/health
              port: {{ $service.port }}
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $service.name }}
spec:
  selector:
    app: {{ $service.name }}
  ports:
    - port: {{ $service.port }}
      targetPort: {{ $service.port }}
{{- end }}