apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "miage-bank.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: "miage-bank.local"
      http:
        paths:
          # Le Front-end
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-front
                port:
                  number: 3000
          # L'API via le Proxy (Gateway)
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-proxy
                port:
                  number: 10000