{{- range $key, $service := .Values.microservices }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "miage-bank.fullname" $ }}-{{ $service.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  publishNotReadyAddresses: true 
  # On utilise ClusterIP par défaut (standard pour les services internes)
  type: ClusterIP 
  ports:
    - port: {{ $service.port }}
      targetPort: {{ $service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ $service.name }}
{{- end }}