apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "miage-bank.fullname" . }}-db-link
spec:
  refreshInterval: "15s"               # Temps de synchro (vu au TP13)
  secretStoreRef:
    name: vault-backend                
    kind: ClusterSecretStore
  target:
    name: miage-bank-db-secret      
    creationPolicy: Owner
  data:
    - secretKey: DB_USER               # Clé que l'appli va lire
      remoteRef:
        key: secret/miage-bank         # Chemin dans Vault
        property: username             # Nom dans Vault
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/miage-bank
        property: password