# ExternalSecret — synchronise les credentials DB depuis Vault
# ESO crée automatiquement le Secret K8s "miage-bank-db-secret"
# à partir des valeurs stockées dans Vault.
# À placer dans : Partie B/01-infrastructure/external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miage-bank-db-external
  namespace: miage-bank
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: miage-bank-db-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: miage-bank/db
        property: mysql-password
    - secretKey: SPRING_DATA_MONGODB_PASSWORD
      remoteRef:
        key: miage-bank/db
        property: mongo-password
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: miage-bank/db
        property: mysql-password
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: miage-bank/db
        property: mongo-password