apiVersion: v2
name: miage-bank
description: Chart Helm pour MIAGE-Bank — architecture micro-services Spring Cloud
type: application
version: 1.0.0
appVersion: "v1"
keywords:
  - miage-bank
  - spring-cloud
  - microservices
  - kubernetes
maintainers:
  - name: RAJAOBELISON Hanja & ALPTEKIN Eylul
