microservices:
  # L'infrastructure d'abord
  annuaire:
    name: annuaire
    repository: amc_annuaire
    tag: latest
    port: 10001
  configserver:
    name: configserver
    repository: amc_configserver
    tag: latest
    port: 10003
  
  # La porte d'entrée
  proxy:
    name: proxy
    repository: amc_proxy
    tag: latest
    port: 10000

  # Les services métiers
  clients:
    name: clients
    repository: amc_clients
    tag: latest
    port: 8080
    hasDatabase: true
    dbType: mysql
  comptes:
    name: comptes
    repository: amc_comptes
    tag: latest
    port: 8080
    hasDatabase: true
    dbType: mongodb
  composite:
    name: composite
    repository: amc_composite
    tag: latest
    port: 8080

  # Le frontend
  front:
    name: front
    repository: amc_front
    tag: latest
    port: 80 # Souvent 80 pour Nginx