FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
# On ajoute cette ligne pour accepter n'importe quel JAR
ARG JAR_FILE
# On utilise la variable ici
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
