name: CI Pipeline Partie A

on:
  push:
    branches: [ "main" ]

jobs:
  audit-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah
          # Installation officielle de Trivy
          wget -qO - https://aquasecurity.github.io/trivy-repo/dabest.gpg | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Build Script
        run: |
          chmod +x ci-scripts/build.sh
          ./ci-scripts/build.sh